# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout/UI/finalizarpdv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_finalizar(object):
    def setupUi(self, finalizar):
        finalizar.setObjectName("finalizar")
        finalizar.setWindowModality(QtCore.Qt.WindowModal)
        finalizar.resize(1036, 721)
        finalizar.setStyleSheet("text-transform: uppercase;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(finalizar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(finalizar)
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color: rgb(0, 0, 0,200);}")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame_6 = QtWidgets.QFrame(self.widget)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 700))
        self.frame_6.setStyleSheet("QFrame#frame_6{\n"
"border-radius:10px;\n"
"background-color: rgb(59, 117, 176);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:white;\n"
"}\n"
"QDoubleSpinBox{\n"
"    font: 900 15pt \"Arial Black\";\n"
"    border:none;\n"
"    color:white;\n"
"    background-color: transparent;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame = QtWidgets.QFrame(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("QFrame{\n"
"    background-color: #2b3157;\n"
"border-radius:8px;\n"
"padding:4px;\n"
"}\n"
"QLineEdit{\n"
"\n"
"color:black;\n"
"border:none;\n"
"}\n"
"\n"
"QGroupBox  {\n"
"    border: 1px solid;\n"
"    border-color: transparent;\n"
"    margin-top: 15px;\n"
"    font-size: 14px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QGroupBox::title  {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    \n"
"    background-color: #FF17365D;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.line_doc = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_doc.sizePolicy().hasHeightForWidth())
        self.line_doc.setSizePolicy(sizePolicy)
        self.line_doc.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line_doc.setFont(font)
        self.line_doc.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line_doc.setInputMask("")
        self.line_doc.setAlignment(QtCore.Qt.AlignCenter)
        self.line_doc.setObjectName("line_doc")
        self.verticalLayout_6.addWidget(self.line_doc)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.db_valorDocumento = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.db_valorDocumento.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.db_valorDocumento.setStyleSheet("QDoubleSpinBox{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
" selection-background-color: darkgray;\n"
"}\n"
"\n"
"QDoubleSpinBox:focus{\n"
"    \n"
"    background-color: rgb(227, 227, 227);\n"
"}")
        self.db_valorDocumento.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.db_valorDocumento.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_valorDocumento.setProperty("showGroupSeparator", True)
        self.db_valorDocumento.setMaximum(999999999.0)
        self.db_valorDocumento.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.db_valorDocumento.setObjectName("db_valorDocumento")
        self.horizontalLayout_5.addWidget(self.db_valorDocumento)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.tb_formPAgmento = QtWidgets.QTableWidget(self.frame)
        self.tb_formPAgmento.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tb_formPAgmento.setStyleSheet("QHeaderView, QHeaderView::section {\n"
"   color:white;\n"
"    background-color: #d3d7e4;\n"
"    font: 10pt \"Segoe UI\";\n"
"color:black;\n"
"border:none;\n"
"\n"
"}\n"
"\n"
"QTableWidget{\n"
"    \n"
"    font: 11pt \"Segoe UI\";\n"
"    selection-background-color: rgb(234, 110, 60);\n"
"}\n"
"")
        self.tb_formPAgmento.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_formPAgmento.setTabKeyNavigation(False)
        self.tb_formPAgmento.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tb_formPAgmento.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_formPAgmento.setObjectName("tb_formPAgmento")
        self.tb_formPAgmento.setColumnCount(4)
        self.tb_formPAgmento.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_formPAgmento.setItem(4, 3, item)
        self.tb_formPAgmento.horizontalHeader().setCascadingSectionResizes(False)
        self.tb_formPAgmento.horizontalHeader().setDefaultSectionSize(80)
        self.tb_formPAgmento.horizontalHeader().setSortIndicatorShown(False)
        self.tb_formPAgmento.horizontalHeader().setStretchLastSection(False)
        self.tb_formPAgmento.verticalHeader().setVisible(False)
        self.tb_formPAgmento.verticalHeader().setCascadingSectionResizes(False)
        self.tb_formPAgmento.verticalHeader().setHighlightSections(True)
        self.verticalLayout_3.addWidget(self.tb_formPAgmento)
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame_8.setStyleSheet("QFrame{\n"
"        background-color: #2b3157;\n"
"border-radius:8px;\n"
"padding:4px;\n"
"}\n"
"QLineEdit{\n"
"    \n"
"    font: 900 10pt \"Arial Black\";\n"
"coloir:balck;\n"
"border:none;\n"
"}\n"
"QLineEdit:focus {\n"
"  border: 1px solid #d0e3ff;\n"
"    background-color: rgb(255, 255, 127);\n"
"}\n"
"QLineEdit::placeholder {\n"
"  color: #767e89;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_2 = QtWidgets.QFrame(self.frame_8)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_cod_cliente = QtWidgets.QLineEdit(self.frame_2)
        self.line_cod_cliente.setMinimumSize(QtCore.QSize(0, 40))
        self.line_cod_cliente.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.line_cod_cliente.setFont(font)
        self.line_cod_cliente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line_cod_cliente.setText("")
        self.line_cod_cliente.setAlignment(QtCore.Qt.AlignCenter)
        self.line_cod_cliente.setReadOnly(True)
        self.line_cod_cliente.setObjectName("line_cod_cliente")
        self.horizontalLayout_2.addWidget(self.line_cod_cliente)
        self.line_nome_cliente = QtWidgets.QLineEdit(self.frame_2)
        self.line_nome_cliente.setMinimumSize(QtCore.QSize(0, 40))
        self.line_nome_cliente.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line_nome_cliente.setStyleSheet("")
        self.line_nome_cliente.setText("")
        self.line_nome_cliente.setObjectName("line_nome_cliente")
        self.horizontalLayout_2.addWidget(self.line_nome_cliente)
        self.line_cpf = QtWidgets.QLineEdit(self.frame_2)
        self.line_cpf.setMinimumSize(QtCore.QSize(0, 40))
        self.line_cpf.setMaximumSize(QtCore.QSize(100, 16777215))
        self.line_cpf.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line_cpf.setMaxLength(11)
        self.line_cpf.setObjectName("line_cpf")
        self.horizontalLayout_2.addWidget(self.line_cpf)
        self.verticalLayout_11.addWidget(self.frame_2)
        self.line_endereco = QtWidgets.QLineEdit(self.frame_8)
        self.line_endereco.setMinimumSize(QtCore.QSize(0, 40))
        self.line_endereco.setSizeIncrement(QtCore.QSize(0, 40))
        self.line_endereco.setFocusPolicy(QtCore.Qt.NoFocus)
        self.line_endereco.setObjectName("line_endereco")
        self.verticalLayout_11.addWidget(self.line_endereco)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout_8.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.frame_6)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setStyleSheet("QFrame{\n"
"    background-color: #2b3157;\n"
"border-radius:8px;\n"
"padding:4px;\n"
"}\n"
"QLineEdit{\n"
"    background-color:transparent;\n"
"color:white;\n"
"border:none;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.db_troco = QtWidgets.QDoubleSpinBox(self.frame_7)
        self.db_troco.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_troco.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.db_troco.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_troco.setProperty("showGroupSeparator", True)
        self.db_troco.setMaximum(999999999.0)
        self.db_troco.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.db_troco.setObjectName("db_troco")
        self.verticalLayout_5.addWidget(self.db_troco)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setStyleSheet("QFrame{\n"
"    background-color: #2b3157;\n"
"border-radius:8px;\n"
"padding:4px;\n"
"}\n"
"QLineEdit{\n"
"    background-color:transparent;\n"
"color:white;\n"
"border:none;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_9 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_17.addWidget(self.label_9)
        self.db_total_venda = QtWidgets.QDoubleSpinBox(self.frame_11)
        self.db_total_venda.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_total_venda.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.db_total_venda.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_total_venda.setProperty("showGroupSeparator", True)
        self.db_total_venda.setMaximum(999999999.0)
        self.db_total_venda.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.db_total_venda.setProperty("value", 0.0)
        self.db_total_venda.setObjectName("db_total_venda")
        self.verticalLayout_17.addWidget(self.db_total_venda)
        self.verticalLayout_7.addWidget(self.frame_11)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setStyleSheet("QFrame{\n"
"        background-color: #2b3157;\n"
"border-radius:8px;\n"
"padding:4px;\n"
"}\n"
"QPushButton{\n"
"padding:15px;\n"
"    font: 11pt \"Arial\";\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.bt_finalizar = QtWidgets.QPushButton(self.frame_5)
        self.bt_finalizar.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/venda/finalizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_finalizar.setIcon(icon)
        self.bt_finalizar.setIconSize(QtCore.QSize(30, 30))
        self.bt_finalizar.setObjectName("bt_finalizar")
        self.horizontalLayout_6.addWidget(self.bt_finalizar)
        self.bt_cancelar = QtWidgets.QPushButton(self.frame_5)
        self.bt_cancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/venda/cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cancelar.setIcon(icon1)
        self.bt_cancelar.setIconSize(QtCore.QSize(30, 30))
        self.bt_cancelar.setObjectName("bt_cancelar")
        self.horizontalLayout_6.addWidget(self.bt_cancelar)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.horizontalLayout_8.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame_6)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(900, 800))
        self.widget_2.setStyleSheet("QDoubleSpinBox{\n"
"    font: 900 15pt \"Arial Black\";\n"
"    border:none;\n"
"    color:white;\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.addWidget(self.widget_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.widget)
        self.actioncodCliente = QtWidgets.QAction(finalizar)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/venda/lupacliente.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actioncodCliente.setIcon(icon2)
        self.actioncodCliente.setObjectName("actioncodCliente")

        self.retranslateUi(finalizar)
        self.bt_cancelar.clicked.connect(finalizar.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(finalizar)
        finalizar.setTabOrder(self.db_valorDocumento, self.line_nome_cliente)

    def retranslateUi(self, finalizar):
        _translate = QtCore.QCoreApplication.translate
        finalizar.setWindowTitle(_translate("finalizar", "finalizarPdv"))
        self.groupBox_2.setTitle(_translate("finalizar", "cod doc"))
        self.line_doc.setText(_translate("finalizar", "1"))
        self.groupBox_3.setTitle(_translate("finalizar", "valor doc"))
        self.db_valorDocumento.setPrefix(_translate("finalizar", "R$ "))
        item = self.tb_formPAgmento.verticalHeaderItem(0)
        item.setText(_translate("finalizar", "New Row"))
        item = self.tb_formPAgmento.verticalHeaderItem(1)
        item.setText(_translate("finalizar", "New Row"))
        item = self.tb_formPAgmento.verticalHeaderItem(2)
        item.setText(_translate("finalizar", "New Row"))
        item = self.tb_formPAgmento.verticalHeaderItem(3)
        item.setText(_translate("finalizar", "New Row"))
        item = self.tb_formPAgmento.verticalHeaderItem(4)
        item.setText(_translate("finalizar", "New Row"))
        item = self.tb_formPAgmento.horizontalHeaderItem(0)
        item.setText(_translate("finalizar", "cod"))
        item = self.tb_formPAgmento.horizontalHeaderItem(1)
        item.setText(_translate("finalizar", "descricao"))
        item = self.tb_formPAgmento.horizontalHeaderItem(2)
        item.setText(_translate("finalizar", "valor R$"))
        item = self.tb_formPAgmento.horizontalHeaderItem(3)
        item.setText(_translate("finalizar", "Aprazo"))
        __sortingEnabled = self.tb_formPAgmento.isSortingEnabled()
        self.tb_formPAgmento.setSortingEnabled(False)
        item = self.tb_formPAgmento.item(0, 0)
        item.setText(_translate("finalizar", "1"))
        item = self.tb_formPAgmento.item(0, 1)
        item.setText(_translate("finalizar", "dinheiro"))
        item = self.tb_formPAgmento.item(0, 2)
        item.setText(_translate("finalizar", "R$ 0.00"))
        item = self.tb_formPAgmento.item(0, 3)
        item.setText(_translate("finalizar", "N"))
        item = self.tb_formPAgmento.item(1, 0)
        item.setText(_translate("finalizar", "2"))
        item = self.tb_formPAgmento.item(1, 1)
        item.setText(_translate("finalizar", "cartao/credito"))
        item = self.tb_formPAgmento.item(1, 2)
        item.setText(_translate("finalizar", "R$ 0.00"))
        item = self.tb_formPAgmento.item(1, 3)
        item.setText(_translate("finalizar", "N"))
        item = self.tb_formPAgmento.item(2, 0)
        item.setText(_translate("finalizar", "3"))
        item = self.tb_formPAgmento.item(2, 1)
        item.setText(_translate("finalizar", "cartao/debito"))
        item = self.tb_formPAgmento.item(2, 2)
        item.setText(_translate("finalizar", "R$ 0.00"))
        item = self.tb_formPAgmento.item(2, 3)
        item.setText(_translate("finalizar", "N"))
        item = self.tb_formPAgmento.item(3, 0)
        item.setText(_translate("finalizar", "4"))
        item = self.tb_formPAgmento.item(3, 1)
        item.setText(_translate("finalizar", "pix"))
        item = self.tb_formPAgmento.item(3, 2)
        item.setText(_translate("finalizar", "R$ 0.00"))
        item = self.tb_formPAgmento.item(3, 3)
        item.setText(_translate("finalizar", "N"))
        item = self.tb_formPAgmento.item(4, 0)
        item.setText(_translate("finalizar", "5"))
        item = self.tb_formPAgmento.item(4, 1)
        item.setText(_translate("finalizar", "duplicata"))
        item = self.tb_formPAgmento.item(4, 2)
        item.setText(_translate("finalizar", "R$ 0.00"))
        item = self.tb_formPAgmento.item(4, 3)
        item.setText(_translate("finalizar", "S"))
        self.tb_formPAgmento.setSortingEnabled(__sortingEnabled)
        self.line_cod_cliente.setPlaceholderText(_translate("finalizar", "1"))
        self.line_nome_cliente.setPlaceholderText(_translate("finalizar", "CONSUMIDOR FINAL"))
        self.line_cpf.setPlaceholderText(_translate("finalizar", "CPF"))
        self.line_endereco.setPlaceholderText(_translate("finalizar", "ENDEREÇO"))
        self.label.setText(_translate("finalizar", "troco R$"))
        self.db_troco.setPrefix(_translate("finalizar", "R$ "))
        self.label_9.setText(_translate("finalizar", "total Venda"))
        self.db_total_venda.setPrefix(_translate("finalizar", "R$ "))
        self.bt_finalizar.setText(_translate("finalizar", "finalizar(f2)"))
        self.bt_finalizar.setShortcut(_translate("finalizar", "F2"))
        self.bt_cancelar.setText(_translate("finalizar", "cancelar(esc)"))
        self.bt_cancelar.setShortcut(_translate("finalizar", "Esc"))
        self.actioncodCliente.setText(_translate("finalizar", "codCliente"))
        self.actioncodCliente.setToolTip(_translate("finalizar", "Buscar Cliente (F11)"))
        self.actioncodCliente.setShortcut(_translate("finalizar", "Ctrl+F11"))
