# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout/ui/parcelapdv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_parcelapdv(object):
    def setupUi(self, parcelapdv):
        parcelapdv.setObjectName("parcelapdv")
        parcelapdv.resize(474, 498)
        parcelapdv.setStyleSheet("text-transform: uppercase;")
        self.horizontalLayout = QtWidgets.QHBoxLayout(parcelapdv)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parcelapdv)
        self.widget.setStyleSheet("QWidget#widget{\n"
"    background-color: rgb(0, 0, 0,200);}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMaximumSize(QtCore.QSize(500, 500))
        self.widget_2.setStyleSheet("QWidget#widget_2{\n"
"border-radius:10px;\n"
"background-color: rgb(59, 117, 176);\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"color:white;\n"
"}\n"
"QDoubleSpinBox{\n"
"    font: 900 15pt \"Arial Black\";\n"
"    border:none;\n"
"    color:white;\n"
"    background-color: transparent;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"        background-color: #2b3157;\n"
"border-radius:8px;\n"
"padding:4px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cb_parcela = QtWidgets.QComboBox(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cb_parcela.setFont(font)
        self.cb_parcela.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.cb_parcela.setStyleSheet("QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QListView{\n"
"    border:                 none;\n"
"    color:                      rgb(87, 96, 134);\n"
"    background-color:   rgb(255, 255, 255);\n"
"    font-weight:            bold;\n"
"    selection-background-color: rgb(47, 175, 178);\n"
"    show-decoration-selected: 1;\n"
"    margin-left:                -10px;\n"
"    padding-left    :           15px;\n"
"}\n"
"\n"
"QListView::item:hover{\n"
"\n"
"    background-color:   rgb(47, 175, 178);\n"
"    border:                 none;\n"
"}")
        self.cb_parcela.setObjectName("cb_parcela")
        self.cb_parcela.addItem("")
        self.cb_parcela.addItem("")
        self.cb_parcela.addItem("")
        self.cb_parcela.addItem("")
        self.cb_parcela.addItem("")
        self.cb_parcela.addItem("")
        self.verticalLayout.addWidget(self.cb_parcela)
        self.tb_parcela = QtWidgets.QTableWidget(self.widget_2)
        self.tb_parcela.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tb_parcela.setStyleSheet("QHeaderView, QHeaderView::section {\n"
"   color:white;\n"
"    background-color: #d3d7e4;\n"
"    font: 10pt \"Segoe UI\";\n"
"color:black;\n"
"border:none;\n"
"\n"
"}\n"
"\n"
"QTableWidget{\n"
"    \n"
"    font: 11pt \"Segoe UI\";\n"
"    selection-background-color: rgb(234, 110, 60);\n"
"}\n"
"")
        self.tb_parcela.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tb_parcela.setTabKeyNavigation(False)
        self.tb_parcela.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tb_parcela.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tb_parcela.setObjectName("tb_parcela")
        self.tb_parcela.setColumnCount(2)
        self.tb_parcela.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_parcela.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_parcela.setHorizontalHeaderItem(1, item)
        self.tb_parcela.horizontalHeader().setCascadingSectionResizes(False)
        self.tb_parcela.horizontalHeader().setDefaultSectionSize(120)
        self.tb_parcela.horizontalHeader().setSortIndicatorShown(False)
        self.tb_parcela.horizontalHeader().setStretchLastSection(True)
        self.tb_parcela.verticalHeader().setVisible(False)
        self.tb_parcela.verticalHeader().setCascadingSectionResizes(False)
        self.tb_parcela.verticalHeader().setHighlightSections(True)
        self.verticalLayout.addWidget(self.tb_parcela)
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setStyleSheet("QFrame{\n"
"        background-color: #2b3157;\n"
"border-radius:8px;\n"
"padding:4px;\n"
"}\n"
"QPushButton{\n"
"padding:15px;\n"
"    font: 11pt \"Arial\";\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bt_geraparcela = QtWidgets.QPushButton(self.frame)
        self.bt_geraparcela.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/venda/engrenagem.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_geraparcela.setIcon(icon)
        self.bt_geraparcela.setIconSize(QtCore.QSize(40, 40))
        self.bt_geraparcela.setObjectName("bt_geraparcela")
        self.horizontalLayout_4.addWidget(self.bt_geraparcela)
        self.bt_imprimir = QtWidgets.QPushButton(self.frame)
        self.bt_imprimir.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/venda/imprimir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_imprimir.setIcon(icon1)
        self.bt_imprimir.setIconSize(QtCore.QSize(40, 40))
        self.bt_imprimir.setObjectName("bt_imprimir")
        self.horizontalLayout_4.addWidget(self.bt_imprimir)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(parcelapdv)
        QtCore.QMetaObject.connectSlotsByName(parcelapdv)

    def retranslateUi(self, parcelapdv):
        _translate = QtCore.QCoreApplication.translate
        parcelapdv.setWindowTitle(_translate("parcelapdv", "parcelapdv"))
        self.label.setText(_translate("parcelapdv", "parcela Venda"))
        self.cb_parcela.setItemText(0, _translate("parcelapdv", "1X"))
        self.cb_parcela.setItemText(1, _translate("parcelapdv", "2X"))
        self.cb_parcela.setItemText(2, _translate("parcelapdv", "3X"))
        self.cb_parcela.setItemText(3, _translate("parcelapdv", "4X"))
        self.cb_parcela.setItemText(4, _translate("parcelapdv", "5X"))
        self.cb_parcela.setItemText(5, _translate("parcelapdv", "6X"))
        item = self.tb_parcela.horizontalHeaderItem(0)
        item.setText(_translate("parcelapdv", "data"))
        item = self.tb_parcela.horizontalHeaderItem(1)
        item.setText(_translate("parcelapdv", "valor r$"))
        self.bt_geraparcela.setText(_translate("parcelapdv", "gerar (f2)"))
        self.bt_geraparcela.setShortcut(_translate("parcelapdv", "F2"))
        self.bt_imprimir.setText(_translate("parcelapdv", "imprimir (ctrl+p)"))
        self.bt_imprimir.setShortcut(_translate("parcelapdv", "Ctrl+P"))
