# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout/ui/pdv.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pdv_sistem(object):
    def setupUi(self, pdv_sistem):
        pdv_sistem.setObjectName("pdv_sistem")
        pdv_sistem.setEnabled(True)
        pdv_sistem.resize(1536, 814)
        pdv_sistem.setStyleSheet("\n"
"QMenuBar{\n"
"  background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"\n"
"QMenuBar::item {\n"
"color : white;\n"
"margin-top:4px;\n"
"spacing: 3px;\n"
"padding: 1px 10px;\n"
"background: transparent;\n"
"border-radius: 4px;\n"
"}\n"
"QMenuBar::item:selected { /* when selected using mouse or keyboard */\n"
"    background-color: rgb(85, 170, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"QMenu {\n"
"    \n"
"    background-color: rgb(85, 170, 255);\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(pdv_sistem)
        self.centralwidget.setStyleSheet("text-transform: uppercase;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_tela = QtWidgets.QWidget(self.centralwidget)
        self.widget_tela.setStyleSheet("QWidget#widget_tela{\n"
"\n"
"\n"
"background-color: rgb(59, 117, 176);\n"
"\n"
"\n"
"}")
        self.widget_tela.setObjectName("widget_tela")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_tela)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.widget_tela)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame.setStyleSheet("QFrame{background-color: #2b3157;\n"
"\n"
"}\n"
"QPushButton{\n"
"background-color: #2b3157;\n"
"border:none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_logo = QtWidgets.QFrame(self.frame)
        self.frame_logo.setMinimumSize(QtCore.QSize(100, 50))
        self.frame_logo.setStyleSheet("image: url(:/logo/pdv.png);")
        self.frame_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.horizontalLayout.addWidget(self.frame_logo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lb_caixa_livre = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.lb_caixa_livre.setFont(font)
        self.lb_caixa_livre.setStyleSheet("color: rgb(255, 255, 255);")
        self.lb_caixa_livre.setObjectName("lb_caixa_livre")
        self.horizontalLayout.addWidget(self.lb_caixa_livre)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bt_minize = QtWidgets.QPushButton(self.frame)
        self.bt_minize.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_minize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/botoestop/minimze.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minize.setIcon(icon)
        self.bt_minize.setIconSize(QtCore.QSize(35, 35))
        self.bt_minize.setObjectName("bt_minize")
        self.horizontalLayout.addWidget(self.bt_minize)
        self.bt_close = QtWidgets.QPushButton(self.frame)
        self.bt_close.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bt_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/botoestop/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_close.setIcon(icon1)
        self.bt_close.setIconSize(QtCore.QSize(40, 45))
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout.addWidget(self.bt_close)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_fundo_tela = QtWidgets.QFrame(self.widget_tela)
        self.frame_fundo_tela.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fundo_tela.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fundo_tela.setObjectName("frame_fundo_tela")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_fundo_tela)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_fundo_tela)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.venda = QtWidgets.QWidget()
        self.venda.setStyleSheet("")
        self.venda.setObjectName("venda")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.venda)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pdv_cod_frame = QtWidgets.QFrame(self.venda)
        self.pdv_cod_frame.setMaximumSize(QtCore.QSize(400, 16777215))
        self.pdv_cod_frame.setStyleSheet("QFrame#pdv_cod_frame{\n"
"\n"
"background-color: rgb(59, 117, 176);\n"
"}\n"
"QLabel{\n"
"color:white;\n"
"\n"
"}\n"
"QDoubleSpinBox{\n"
"    font: 900 15pt \"Arial Black\";\n"
"    border:none;\n"
"    color:white;\n"
"    background-color: transparent;\n"
"}")
        self.pdv_cod_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pdv_cod_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pdv_cod_frame.setObjectName("pdv_cod_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.pdv_cod_frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_2 = QtWidgets.QFrame(self.pdv_cod_frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 130))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: #2b3157;\n"
"border-radius:8px;\n"
"padding:4px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_14.addWidget(self.label_3)
        self.line_produto = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_produto.sizePolicy().hasHeightForWidth())
        self.line_produto.setSizePolicy(sizePolicy)
        self.line_produto.setMinimumSize(QtCore.QSize(0, 40))
        self.line_produto.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line_produto.setFont(font)
        self.line_produto.setStyleSheet("\n"
"QLineEdit:focus{\n"
"    \n"
"    background-color: rgb(255, 255, 127);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.line_produto.setObjectName("line_produto")
        self.verticalLayout_14.addWidget(self.line_produto)
        self.verticalLayout_13.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.pdv_cod_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_5.setStyleSheet("QFrame{\n"
"    background-color: #2b3157;\n"
"border-radius:10px;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.db_quantidade = QtWidgets.QDoubleSpinBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_quantidade.sizePolicy().hasHeightForWidth())
        self.db_quantidade.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        self.db_quantidade.setFont(font)
        self.db_quantidade.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.db_quantidade.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.db_quantidade.setStyleSheet("\n"
"QDoubleSpinBox:focus{\n"
"    \n"
"    background-color: rgb(255, 255, 127);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.db_quantidade.setFrame(True)
        self.db_quantidade.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.db_quantidade.setReadOnly(False)
        self.db_quantidade.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_quantidade.setKeyboardTracking(True)
        self.db_quantidade.setProperty("showGroupSeparator", False)
        self.db_quantidade.setDecimals(3)
        self.db_quantidade.setMaximum(99999999999999.0)
        self.db_quantidade.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.db_quantidade.setProperty("value", 1.0)
        self.db_quantidade.setObjectName("db_quantidade")
        self.verticalLayout_6.addWidget(self.db_quantidade)
        self.verticalLayout_13.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.pdv_cod_frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: #2b3157;\n"
"border-radius:10px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_15.addWidget(self.label_4)
        self.db_quantidade_itens = QtWidgets.QDoubleSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_quantidade_itens.sizePolicy().hasHeightForWidth())
        self.db_quantidade_itens.setSizePolicy(sizePolicy)
        self.db_quantidade_itens.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_quantidade_itens.setFrame(False)
        self.db_quantidade_itens.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.db_quantidade_itens.setReadOnly(True)
        self.db_quantidade_itens.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_quantidade_itens.setKeyboardTracking(True)
        self.db_quantidade_itens.setProperty("showGroupSeparator", True)
        self.db_quantidade_itens.setDecimals(2)
        self.db_quantidade_itens.setMaximum(99999999999999.0)
        self.db_quantidade_itens.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.db_quantidade_itens.setObjectName("db_quantidade_itens")
        self.verticalLayout_15.addWidget(self.db_quantidade_itens)
        self.verticalLayout_13.addWidget(self.frame_3)
        self.frame_6 = QtWidgets.QFrame(self.pdv_cod_frame)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_6.setStyleSheet("QFrame{\n"
"    background-color: #2b3157;\n"
"border-radius:10px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.db_total_unitario = QtWidgets.QDoubleSpinBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_total_unitario.sizePolicy().hasHeightForWidth())
        self.db_total_unitario.setSizePolicy(sizePolicy)
        self.db_total_unitario.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.db_total_unitario.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_total_unitario.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.db_total_unitario.setReadOnly(True)
        self.db_total_unitario.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_total_unitario.setProperty("showGroupSeparator", True)
        self.db_total_unitario.setDecimals(2)
        self.db_total_unitario.setMaximum(99999999999999.0)
        self.db_total_unitario.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.db_total_unitario.setObjectName("db_total_unitario")
        self.verticalLayout_4.addWidget(self.db_total_unitario)
        self.verticalLayout_13.addWidget(self.frame_6)
        self.frame_8 = QtWidgets.QFrame(self.pdv_cod_frame)
        self.frame_8.setStyleSheet("QFrame{\n"
"    background-color: #2b3157;\n"
"border-radius:10px;\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.db_desconto = QtWidgets.QDoubleSpinBox(self.frame_8)
        self.db_desconto.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_desconto.setStyleSheet("\n"
"QDoubleSpinBox:focus{\n"
"    \n"
"    background-color: rgb(255, 255, 127);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.db_desconto.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.db_desconto.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_desconto.setProperty("showGroupSeparator", True)
        self.db_desconto.setMaximum(999999999.0)
        self.db_desconto.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.db_desconto.setObjectName("db_desconto")
        self.verticalLayout_7.addWidget(self.db_desconto)
        self.verticalLayout_13.addWidget(self.frame_8)
        self.logo = QtWidgets.QFrame(self.pdv_cod_frame)
        self.logo.setMinimumSize(QtCore.QSize(50, 200))
        self.logo.setStyleSheet("border-image: url(:/logo/pdv.png);")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.verticalLayout_13.addWidget(self.logo)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.pdv_cod_frame)
        self.frame_fundopdv = QtWidgets.QFrame(self.venda)
        self.frame_fundopdv.setStyleSheet("QFrame#frame_fundopdv{\n"
"border:4px solid  #2b3157;\n"
"}")
        self.frame_fundopdv.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_fundopdv.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_fundopdv.setObjectName("frame_fundopdv")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_fundopdv)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.frame_fundopdv)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #2b3157;\n"
"color:white;\n"
"padding:15px")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.tab_itens = QtWidgets.QTableWidget(self.frame_fundopdv)
        self.tab_itens.setEnabled(True)
        self.tab_itens.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tab_itens.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tab_itens.setStyleSheet("QHeaderView, QHeaderView::section {\n"
"   color:white;\n"
"    background-color: #d3d7e4;\n"
"    font: 10pt \"Segoe UI\";\n"
"color:black;\n"
"border:none;\n"
"\n"
"}\n"
"\n"
"QTableWidget{\n"
"    \n"
"    font: 11pt \"Segoe UI\";\n"
"    selection-background-color: rgb(234, 110, 60);\n"
"}\n"
"")
        self.tab_itens.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab_itens.setTabKeyNavigation(False)
        self.tab_itens.setProperty("showDropIndicator", True)
        self.tab_itens.setDragEnabled(False)
        self.tab_itens.setDragDropOverwriteMode(True)
        self.tab_itens.setAlternatingRowColors(False)
        self.tab_itens.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tab_itens.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tab_itens.setShowGrid(False)
        self.tab_itens.setObjectName("tab_itens")
        self.tab_itens.setColumnCount(8)
        self.tab_itens.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tab_itens.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_itens.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_itens.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_itens.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_itens.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_itens.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_itens.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_itens.setHorizontalHeaderItem(7, item)
        self.tab_itens.horizontalHeader().setStretchLastSection(True)
        self.tab_itens.verticalHeader().setVisible(False)
        self.tab_itens.verticalHeader().setHighlightSections(True)
        self.verticalLayout_8.addWidget(self.tab_itens)
        self.frame_7 = QtWidgets.QFrame(self.frame_fundopdv)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_7.setStyleSheet("QFrame{background-color: #2b3157;\n"
"color:white;}\n"
"\n"
"\n"
"QDoubleSpinBox{\n"
"    font: 900 45pt \"Arial Black\";\n"
"    border:none;\n"
"color:white;\n"
"background-color: #2b3157;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.db_total_venda = QtWidgets.QDoubleSpinBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_total_venda.sizePolicy().hasHeightForWidth())
        self.db_total_venda.setSizePolicy(sizePolicy)
        self.db_total_venda.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.db_total_venda.setFocusPolicy(QtCore.Qt.NoFocus)
        self.db_total_venda.setStyleSheet("")
        self.db_total_venda.setWrapping(False)
        self.db_total_venda.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.db_total_venda.setReadOnly(True)
        self.db_total_venda.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.db_total_venda.setProperty("showGroupSeparator", True)
        self.db_total_venda.setDecimals(2)
        self.db_total_venda.setMaximum(99999999999999.0)
        self.db_total_venda.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.db_total_venda.setObjectName("db_total_venda")
        self.verticalLayout_5.addWidget(self.db_total_venda)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.horizontalLayout_5.addWidget(self.frame_fundopdv)
        self.stackedWidget.addWidget(self.venda)
        self.estoque = QtWidgets.QWidget()
        self.estoque.setStyleSheet("")
        self.estoque.setObjectName("estoque")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.estoque)
        self.verticalLayout_10.setContentsMargins(0, 5, 5, 5)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_estoque_pdv = QtWidgets.QFrame(self.estoque)
        self.frame_estoque_pdv.setStyleSheet("QFrame#frame_estoque_pdv{\n"
"border:4px solid  #2b3157;\n"
"}")
        self.frame_estoque_pdv.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_estoque_pdv.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_estoque_pdv.setObjectName("frame_estoque_pdv")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_estoque_pdv)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label = QtWidgets.QLabel(self.frame_estoque_pdv)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #2b3157;\n"
"color:white;\n"
"padding:15px")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_12.addWidget(self.label)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_estoque_pdv)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_6.setStyleSheet("QGroupBox  {\n"
"    border: 1px solid gray;\n"
"    border-color: #FF17365D;\n"
"    margin-top: 12px;\n"
"    font-size: 14px;\n"
"    border-radius: 5px;\n"
"\n"
"}\n"
"QGroupBox::title  {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top LEFT;\n"
"\n"
"}")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setContentsMargins(0, -1, 0, 1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_estoque = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_estoque.sizePolicy().hasHeightForWidth())
        self.line_estoque.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_estoque.setFont(font)
        self.line_estoque.setFocusPolicy(QtCore.Qt.TabFocus)
        self.line_estoque.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.line_estoque.setObjectName("line_estoque")
        self.horizontalLayout_6.addWidget(self.line_estoque)
        self.verticalLayout_12.addWidget(self.groupBox_6)
        self.tab_estoque_itens = QtWidgets.QTableWidget(self.frame_estoque_pdv)
        self.tab_estoque_itens.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tab_estoque_itens.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tab_estoque_itens.setStyleSheet("QHeaderView, QHeaderView::section {\n"
"   color:white;\n"
"    background-color: #d3d7e4;\n"
"    font: 10pt \"Segoe UI\";\n"
"color:black;\n"
"border:none;\n"
"\n"
"}\n"
"\n"
"QTableWidget{\n"
"\n"
"    font: 11pt \"Segoe UI\";\n"
"    selection-background-color: rgb(234, 110, 60);\n"
"}\n"
"")
        self.tab_estoque_itens.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab_estoque_itens.setTabKeyNavigation(False)
        self.tab_estoque_itens.setProperty("showDropIndicator", False)
        self.tab_estoque_itens.setDragDropOverwriteMode(False)
        self.tab_estoque_itens.setAlternatingRowColors(False)
        self.tab_estoque_itens.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.tab_estoque_itens.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tab_estoque_itens.setShowGrid(True)
        self.tab_estoque_itens.setWordWrap(False)
        self.tab_estoque_itens.setCornerButtonEnabled(False)
        self.tab_estoque_itens.setObjectName("tab_estoque_itens")
        self.tab_estoque_itens.setColumnCount(7)
        self.tab_estoque_itens.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tab_estoque_itens.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_estoque_itens.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_estoque_itens.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_estoque_itens.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_estoque_itens.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_estoque_itens.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_estoque_itens.setHorizontalHeaderItem(6, item)
        self.tab_estoque_itens.horizontalHeader().setStretchLastSection(True)
        self.tab_estoque_itens.verticalHeader().setVisible(False)
        self.tab_estoque_itens.verticalHeader().setHighlightSections(True)
        self.verticalLayout_12.addWidget(self.tab_estoque_itens)
        self.verticalLayout_10.addWidget(self.frame_estoque_pdv)
        self.stackedWidget.addWidget(self.estoque)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_fundo_tela)
        self.frame_botoes = QtWidgets.QFrame(self.widget_tela)
        self.frame_botoes.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_botoes.setStyleSheet("QFrame{background-color: #2b3157;\n"
"\n"
"}\n"
"QPushButton{\n"
"padding:15px;\n"
"    font: 11pt \"Arial\";\n"
"}\n"
"QToolButton{\n"
"padding:15px;\n"
"    font: 11pt \"Arial\";\n"
"}")
        self.frame_botoes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_botoes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_botoes.setObjectName("frame_botoes")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_botoes)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.tb_finalizar = QtWidgets.QPushButton(self.frame_botoes)
        self.tb_finalizar.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/venda/finalizar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_finalizar.setIcon(icon2)
        self.tb_finalizar.setIconSize(QtCore.QSize(25, 25))
        self.tb_finalizar.setObjectName("tb_finalizar")
        self.horizontalLayout_3.addWidget(self.tb_finalizar)
        self.tb_cancelar = QtWidgets.QPushButton(self.frame_botoes)
        self.tb_cancelar.setFocusPolicy(QtCore.Qt.NoFocus)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/venda/cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_cancelar.setIcon(icon3)
        self.tb_cancelar.setIconSize(QtCore.QSize(25, 25))
        self.tb_cancelar.setObjectName("tb_cancelar")
        self.horizontalLayout_3.addWidget(self.tb_cancelar)
        self.bt_delete_produto = QtWidgets.QPushButton(self.frame_botoes)
        self.bt_delete_produto.setFocusPolicy(QtCore.Qt.NoFocus)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/venda/excluir.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_delete_produto.setIcon(icon4)
        self.bt_delete_produto.setIconSize(QtCore.QSize(25, 25))
        self.bt_delete_produto.setObjectName("bt_delete_produto")
        self.horizontalLayout_3.addWidget(self.bt_delete_produto)
        self.tb_sangria = QtWidgets.QPushButton(self.frame_botoes)
        self.tb_sangria.setFocusPolicy(QtCore.Qt.NoFocus)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/venda/sangria.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_sangria.setIcon(icon5)
        self.tb_sangria.setIconSize(QtCore.QSize(25, 25))
        self.tb_sangria.setObjectName("tb_sangria")
        self.horizontalLayout_3.addWidget(self.tb_sangria)
        self.tool_menu = QtWidgets.QToolButton(self.frame_botoes)
        self.tool_menu.setFocusPolicy(QtCore.Qt.NoFocus)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/venda/engrenagem.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_menu.setIcon(icon6)
        self.tool_menu.setIconSize(QtCore.QSize(25, 25))
        self.tool_menu.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.tool_menu.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tool_menu.setAutoRaise(False)
        self.tool_menu.setArrowType(QtCore.Qt.NoArrow)
        self.tool_menu.setObjectName("tool_menu")
        self.horizontalLayout_3.addWidget(self.tool_menu)
        self.verticalLayout_2.addWidget(self.frame_botoes)
        self.verticalLayout.addWidget(self.widget_tela)
        self.rodape = QtWidgets.QFrame(self.centralwidget)
        self.rodape.setStyleSheet("QFrame{background-color: #2b3157;\n"
"\n"
"}\n"
"QLabel{\n"
"color:white;\n"
"    font: 900 9pt \"Arial Black\";\n"
"}")
        self.rodape.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rodape.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rodape.setObjectName("rodape")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.rodape)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lb_nome_user = QtWidgets.QLabel(self.rodape)
        self.lb_nome_user.setText("")
        self.lb_nome_user.setObjectName("lb_nome_user")
        self.horizontalLayout_7.addWidget(self.lb_nome_user)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.lb_ip = QtWidgets.QLabel(self.rodape)
        self.lb_ip.setText("")
        self.lb_ip.setObjectName("lb_ip")
        self.horizontalLayout_7.addWidget(self.lb_ip)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.lb_data_emissao = QtWidgets.QLabel(self.rodape)
        self.lb_data_emissao.setObjectName("lb_data_emissao")
        self.horizontalLayout_7.addWidget(self.lb_data_emissao)
        self.verticalLayout.addWidget(self.rodape)
        pdv_sistem.setCentralWidget(self.centralwidget)
        self.actionCadastro_Cliente = QtWidgets.QAction(pdv_sistem)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/menupdv/cliente.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastro_Cliente.setIcon(icon7)
        self.actionCadastro_Cliente.setObjectName("actionCadastro_Cliente")
        self.actionCadastro_Produto = QtWidgets.QAction(pdv_sistem)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/menupdv/estoque.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCadastro_Produto.setIcon(icon8)
        self.actionCadastro_Produto.setObjectName("actionCadastro_Produto")

        self.retranslateUi(pdv_sistem)
        self.stackedWidget.setCurrentIndex(0)
        self.bt_close.clicked.connect(pdv_sistem.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(pdv_sistem)

    def retranslateUi(self, pdv_sistem):
        _translate = QtCore.QCoreApplication.translate
        pdv_sistem.setWindowTitle(_translate("pdv_sistem", "pdv_vendas"))
        self.lb_caixa_livre.setText(_translate("pdv_sistem", "CAIXA LIVRE"))
        self.label_3.setText(_translate("pdv_sistem", "F12 Buscar PRodutos|CODIGO PRODUTO | DESCRICAO|REFERENCIA"))
        self.label_5.setText(_translate("pdv_sistem", "Qtd inser:"))
        self.label_4.setText(_translate("pdv_sistem", "quantidade itens grade"))
        self.label_6.setText(_translate("pdv_sistem", "total do item r$"))
        self.db_total_unitario.setPrefix(_translate("pdv_sistem", " R$ "))
        self.label_8.setText(_translate("pdv_sistem", "desconto % (F12)"))
        self.db_desconto.setPrefix(_translate("pdv_sistem", "% "))
        self.label_2.setText(_translate("pdv_sistem", "lista de produtos"))
        item = self.tab_itens.horizontalHeaderItem(0)
        item.setText(_translate("pdv_sistem", "CODIGO"))
        item = self.tab_itens.horizontalHeaderItem(1)
        item.setText(_translate("pdv_sistem", "DESCRICAO"))
        item = self.tab_itens.horizontalHeaderItem(2)
        item.setText(_translate("pdv_sistem", "QTD"))
        item = self.tab_itens.horizontalHeaderItem(3)
        item.setText(_translate("pdv_sistem", "UNID"))
        item = self.tab_itens.horizontalHeaderItem(4)
        item.setText(_translate("pdv_sistem", "PREÇO R$"))
        item = self.tab_itens.horizontalHeaderItem(5)
        item.setText(_translate("pdv_sistem", "TOTAL ITEM R$"))
        item = self.tab_itens.horizontalHeaderItem(6)
        item.setText(_translate("pdv_sistem", "D"))
        self.label_7.setText(_translate("pdv_sistem", "total VENDA r$"))
        self.db_total_venda.setPrefix(_translate("pdv_sistem", "R$ "))
        self.label.setText(_translate("pdv_sistem", "estoque"))
        self.groupBox_6.setTitle(_translate("pdv_sistem", "CODIGO PRODUTO | DESCRICAO"))
        self.line_estoque.setPlaceholderText(_translate("pdv_sistem", "estoque"))
        item = self.tab_estoque_itens.horizontalHeaderItem(0)
        item.setText(_translate("pdv_sistem", "CODIGO"))
        item = self.tab_estoque_itens.horizontalHeaderItem(1)
        item.setText(_translate("pdv_sistem", "DESCRICAO"))
        item = self.tab_estoque_itens.horizontalHeaderItem(2)
        item.setText(_translate("pdv_sistem", "qtd"))
        item = self.tab_estoque_itens.horizontalHeaderItem(3)
        item.setText(_translate("pdv_sistem", "custo"))
        item = self.tab_estoque_itens.horizontalHeaderItem(4)
        item.setText(_translate("pdv_sistem", "venda"))
        item = self.tab_estoque_itens.horizontalHeaderItem(5)
        item.setText(_translate("pdv_sistem", "tributo"))
        self.tb_finalizar.setText(_translate("pdv_sistem", "FINALIZAR(F2)"))
        self.tb_finalizar.setShortcut(_translate("pdv_sistem", "F2"))
        self.tb_cancelar.setText(_translate("pdv_sistem", "CANCELAR(F6)"))
        self.tb_cancelar.setShortcut(_translate("pdv_sistem", "F6"))
        self.bt_delete_produto.setText(_translate("pdv_sistem", "delete (-)"))
        self.bt_delete_produto.setShortcut(_translate("pdv_sistem", "-"))
        self.tb_sangria.setText(_translate("pdv_sistem", "SANGRIA(F9)"))
        self.tb_sangria.setShortcut(_translate("pdv_sistem", "F9"))
        self.tool_menu.setText(_translate("pdv_sistem", "opçao"))
        self.tool_menu.setShortcut(_translate("pdv_sistem", "F1"))
        self.lb_data_emissao.setText(_translate("pdv_sistem", "TextLabel"))
        self.actionCadastro_Cliente.setText(_translate("pdv_sistem", "Cadastro Cliente"))
        self.actionCadastro_Produto.setText(_translate("pdv_sistem", "Cadastro Produto"))
